In [43]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import classification_report,confusion_matrix

Data Loading and Exploration: a. Load the dataset and perform initial exploratory data analysis (EDA) to understand the structure and characteristics of the data. b. Visualize the relationships between the independent variables (LotArea, BedroomAbvGr, FullBath, YearBuilt) and the target variable (Price).

In [16]:
train = pd.read_csv('train.csv')
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [14]:
test = pd.read_csv('test.csv')
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [7]:
sample = pd.read_csv('sample_submission.csv')
sample

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

Data Preprocessing: a. Handle any missing values in the dataset using an appropriate strategy. b. Scale the numerical features using standardization (Z-score scaling).

In [21]:
train.fillna(train.median(), inplace=True)
test.fillna(test.median(), inplace=True)

C:\Users\Arman\AppData\Local\Temp\ipykernel_5688\691725056.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  train.fillna(train.median(), inplace=True)
C:\Users\Arman\AppData\Local\Temp\ipykernel_5688\691725056.py:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  test.fillna(test.median(), inplace=True)

In this code cell we filling Nan values of our train and test datas with data median value.

Merge sample_submission.csv to test.csv to get the actual SalesPrice for test set.

In [10]:
merged_df = pd.merge(test, sample, how='outer')
merged_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,169277.052498
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,187758.393989
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,183583.683570
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,179317.477511
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,150730.079977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,167081.220949
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,164788.778231
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,219222.423400
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,184924.279659
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,187741.866657

We merge test data with sample submission data to have a whole data set with independent values and our output value "SalePrice".

In [30]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(train[['LotArea', 'BedroomAbvGr', 'FullBath', 'YearBuilt']])
scaled_data

array([[-0.20714171,  0.16377912,  0.78974052,  1.05099379],
       [-0.09188637,  0.16377912,  0.78974052,  0.15673371],
       [ 0.07347998,  0.16377912,  0.78974052,  0.9847523 ],
       ...,
       [-0.14781027,  1.39002276,  0.78974052, -1.00249232],
       [-0.08016039, -1.06246453, -1.02604084, -0.70440562],
       [-0.05811155,  0.16377912, -1.02604084, -0.20759447]])

In [51]:
scaled_data_2 = scaler.fit_transform(test[['LotArea', 'BedroomAbvGr', 'FullBath', 'YearBuilt']])
scaled_data_2

array([[ 0.36392912, -1.02954254, -1.02871967, -0.34094461],
       [ 0.89786065,  0.17599724, -1.02871967, -0.43969491],
       [ 0.80964587,  0.17599724,  0.77308345,  0.844059  ],
       ...,
       [ 2.05514965,  1.38153702, -1.02871967, -0.37386137],
       [ 0.12552719,  0.17599724, -1.02871967,  0.67947517],
       [-0.03879049,  0.17599724,  0.77308345,  0.71239193]])

we create Stadard Scaler function becuase want to have zero-mean, unit standard-deviation of each feature

In [24]:
X = train[['LotArea', 'BedroomAbvGr', 'FullBath', 'YearBuilt']]
y = train['SalePrice']

Model Building: a. Split the dataset into features (X) and the target variable (y). b. Implement a KNN regression model. Start with a reasonable default value for k. c. Use cross-validation (e.g., k-fold cross-validation) to evaluate the model's performance. Choose an appropriate evaluation metric for regression (e.g., mean squared error or mean absolute error).

In [36]:
knn_regressor = KNeighborsRegressor()
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
}

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [37]:
grid_search = GridSearchCV(knn_regressor, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [3, 5, 7, 9], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='neg_mean_squared_error')

We built our model with KNN regressor,with amount of parameters to train

Hyperparameter Tuning: a. Implement a grid search or random search to tune the hyperparameters of the KNN regressor. Experiment with different values of k and distance metrics (e.g., Euclidean, Manhattan). b. Determine the best combination of hyperparameters based on the cross-validation results.

In [41]:
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

Best Hyperparameters: {'n_neighbors': 9, 'p': 1, 'weights': 'distance'}

In [40]:
best_knn_regressor = KNeighborsRegressor(n_neighbors=best_params['n_neighbors'],
                                          weights=best_params['weights'],
                                          p=best_params['p'])

In [44]:
best_knn_regressor.fit(X_train, y_train)
y_pred = best_knn_regressor.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 4515739767.05024
R-squared: 0.26784631529280345

We have done hyperparameter tuning and found out best parameters from given list

Model Evaluation: a. Train the KNN regressor using the best hyperparameters identified. b. Evaluate the model's performance on a held-out test set using the chosen evaluation metric.

In [48]:
X_test = test[['LotArea', 'BedroomAbvGr', 'FullBath', 'YearBuilt']]
y_pred = best_knn_regressor.predict(X_test)

In [50]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(sample['SalePrice'], y_pred)

Interpretation and Insights: Provide a summary of your findings. Discuss how different hyperparameters affect the model's performance and provide insights into the relationships between the features and the target variable.

We found out that the best parameters for this data set are {'n_neighbors': 9, 'p': 1, 'weights': 'distance'} but our model is not very good at all